dist: xenial

env:
  global:
    - PYPI_USERNAME=urllib3

jobs:
  include:
    # Python code quality:
    - language: python
      python: 3.7
      before_install:
        - pip freeze | xargs pip uninstall -y
        - curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
        - source "$HOME/.poetry/env"
      install: poetry install
      script:
        - make test

    # Linting danger, code duplicates, and markdown:
    - language: node_js
      node_js: 10.16
      install: npm install
      script: npm run test

stages:
  - name: test
    if: tag IS blank

  # Run integration tests for release candidates
  - name: integration
    if: type = pull_request AND head_branch =~ ^release-[\d.]+$ AND tag IS blank

  # Deploy on any tags
  - name: deploy
    if: tag IS present AND tag =~ /^(\d+\.\d+(?:.\d+)?)$/ AND repo = urllib3/urllib3

notifications:
  email:
    on_success: never
    on_failure: change
